    name: FTP Deploy

    on:
      push:
        branches:
          - main # Or your desired branch for deployments

    jobs:
      deploy:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4 # Checks out your repository

          - name: FTP Deploy
            uses: samkirkland/ftp-deploy-action@v1.3.0 # Uses the FTP deploy action
            with:
              ftp-host: ${{ secrets.FTP_HOST }}
              ftp-user: ${{ secrets.FTP_USER }}
              ftp-password: ${{ secrets.FTP_PASSWORD }}
              local-dir: ./ # Path to your files in the repository
